name: "Test Quality Gate Policies"
description: "Define policies to control target"
author: "kirinnee"
inputs:
  current:
    required: true
    description: "Current commit metadata"
  base:
    required: false
    description: "Base commit metadata"
  history:
    required: true
    description: "History metadatas for this PR"
  policies:
    required: true
    description: "Quality Gate policies"
    default: "default value if applicable"
outputs:
  current:
    description: "Current Commit's data with quality gate information"
  history:
    description: "History Commits' data with quality gate information"
runs:
  using: "node16"
  main: "dist/index.js"
